import { PageFooter } from "@/components/footer/PageFooter";
import { Navigation } from "@/components/header/Navigation";
import { TopBar } from "@/components/header/TopBar";
import { News } from "@/components/homePage/News";
import { GetStaticProps } from "next";
import Head from "next/head";
import styles from "../styles/MainPageBody.module.css";
import { RootNavigation } from "@/components/header/Types";
import { ImageToSlide } from "@/components/homePage/Types";
import { SeparateSection } from "@/components/homePage/SeparateSection";
import { RecommendedProducts } from "@/components/homePage/recommendedProducts/RecommendedProducts";
import { RecommendedProduct } from "@/components/homePage/recommendedProducts/Types";
import { HotSellProduct } from "@/components/homePage/hotSellPanel/Types";
import { Promotions } from "@/components/homePage/promotions/Promotions";
import { Promotion } from "@/components/homePage/promotions/Types";
import { HitsOfTheWeek } from "@/components/homePage/hitsOfTheWeekSlider/HitsOfTheWeek";
import { HitOfWeekProduct } from "@/components/homePage/hitsOfTheWeekSlider/Types";
import { BestSellers } from "@/components/homePage/bestsellers/BestSellers";
import { BestsellerProduct } from "@/components/homePage/bestsellers/Types";
import axios from "axios";
import { Layout } from "@/components/Layout";

export default function Home(props: {
	navigationData: RootNavigation[];
	advertisementData: ImageToSlide[];
	recommendedProductsData: RecommendedProduct[];
	hotSellProductData: HotSellProduct;
	promotions: Promotion[];
	hitsOfTheWeekProducts: HitOfWeekProduct[];
	bestsellers: BestsellerProduct[];
}) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout navigation={props.navigationData}>
				<News advertising={props.advertisementData} />
				<SeparateSection sectionName="Recomended products" />
				<RecommendedProducts
					recommendedProduct={props.recommendedProductsData}
				/>
				<hr />
				<SeparateSection sectionName="Promotions" url="/promotions" />
				<Promotions promotionsData={props.promotions} />
				<hr />
				<SeparateSection
					sectionName="Hits of the week"
					url="/hitsoftheweek"
				/>
				<HitsOfTheWeek hitsOfTheWeek={props.hitsOfTheWeekProducts} />
				<hr />
				<SeparateSection sectionName="Bestsellers" url="/bestsellers" />
				<BestSellers products={props.bestsellers} />
				<hr />
			</Layout>
		</div>
	);
}

export const getServerSideProps: GetStaticProps = async ({ params }) => {
	// todo error handle
	const urls = [
		"http://localhost:3000/api/navigation/navigation/",
		"http://localhost:3000/api/advertising/advertisement/",
		"http://localhost:3000/api/recommendedProduct/recommendedProduct/",
		"http://localhost:3000/api/promotion/promotion/",
		"http://localhost:3000/api/hitsOfTheWeek/hitsOfTheWeek/",
		"http://localhost:3000/api/bestsellerProduct/bestsellerProduct/",
	];

	const requests = urls.map((url) => axios.get(url));
	const respons = await axios.all(requests);

	return {
		props: {
			navigationData: respons[0].data,
			advertisementData: respons[1].data,
			recommendedProductsData: respons[2].data,
			promotions: respons[3].data,
			hitsOfTheWeekProducts: respons[4].data,
			bestsellers: respons[5].data,
		},
	};
};
