import { GetStaticProps } from "next";
import Head from "next/head";
import { getNewsletterEmails } from "@/server/newsletter/newsletter";
import { PageFooter } from "@/components/footer/PageFooter";

export default function NewsletterEmails(props: { emails: string[] }) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				{props.emails.map((email) => {
					return <p key={email}>{email}</p>;
				})}
			</div>
			<PageFooter />
		</div>
	);
}

export const getStaticProps: GetStaticProps = async () => {
	const [emails] = await Promise.all([getNewsletterEmails()]);

	return {
		props: {
			emails,
		},
	};
};
